### ISSUE TITLE
Tag to disable default lighting in the grid portal.

### ISSUE THREAD

**Issue by Blitzy** [casual-simulation/casualos#303]
Light bot forms got added #291 but their usefulness is hampered by not being able to disable the default lighting of the gridPortal.

I think we should add a `defaultLighting` tag to the `gridPortalBot` that would allow the disabling of the grid portal's default lights.

# Tag
`defaultLighting` - boolean that toggles on/off the default lights in the grid portal. (Defaults to `true`).

**Comment by KallynGowdy** [comment]
Duplicate of #304
