### ISSUE TITLE
Ability to determine what inst a bot belongs to.

### ISSUE THREAD

**Issue by Blitzy** [casual-simulation/casualos#363]
It would be good to be able to determine the inst that any given bot belongs to.

In multi-inst scenarios there are many potential use cases where you would want to know what inst the bot is in, for example when performing and/or receiving a `superShout`.

I am not sure what manifestation of this would be ideal? It could be another special tag or property on bots or maybe as an action function that returns the inst of any given bot?

**Comment by KallynGowdy** [comment]
I think that `os.getCurrentInst()` would ideally be able to handle this for people. Currently this works by placing all the loaded insts into the `inst` tag of the configBot. `os.getCurrentInst()` returns only the first inst in the list, and that might not even be the one that the bot is actually from.

I propose that we change the `inst` tag in the configBot to contain the list of insts, but ordered such that the current inst is always the first element in the array. This way, `os.getCurrentInst()` would always return the correct value.
