### ISSUE TITLE
Add TypeScript Support

### ISSUE THREAD

**Issue by KallynGowdy** [casual-simulation/casualos#383]
Currently, the only way to document types and interfaces for scripts is to use documentation comments. Ideally, users will be able to use TypeScript to properly define types. Additionally, the monaco-editor already supports TypeScript with validation, so supporting TypeScript has the potential to greatly improve user experience with writing scripts.

Currently, we use Acorn as the JavaScript parser. There is a plugin for Acorn that enables parsing TypeScript called [acorn-typescript](https://github.com/TyrealHu/acorn-typescript). This task is to support parsing TypeScript using the plugin and then also implement a transpiler to remove all the TypeScript annotations so that scripts are compiled down to JavaScript for the runtime.

**Comment by Blitzy** [comment]
This would transform large scale projects.
