### ISSUE TITLE
Code editor does not get automatic focus after adding a new tag in the system portal.

### ISSUE THREAD

**Issue by Blitzy** [casual-simulation/casualos#533]
After creating a new tag in the system portal, the code editor no longer gets automatic focus. You have to click into it in order to start typing.

**Comment by KallynGowdy** [comment]
@Blitzy What version of CasualOS are you running? I'm not currently seeing this in v3.3.8.

**Comment by Blitzy** [comment]
Running in v3.3.7

Sorry for the dupe issue this was already fixed in v3.3.8
